// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UntitledTechie.Infrastructure.Data;

namespace UntitledTechie.Infrastructure.Migrations
{
    [DbContext(typeof(TechieContext))]
    partial class TechieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UntitledTechie.Infrastructure.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AvatarImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            AvatarImageId = new Guid("ed28c9f4-05ae-4930-bd15-30dc808438e5"),
                            Username = "TechieAdmin"
                        },
                        new
                        {
                            Id = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            AvatarImageId = new Guid("ed28c9f4-05ae-4930-bd15-30dc808438e5"),
                            Username = "TechieBot"
                        });
                });

            modelBuilder.Entity("UntitledTechie.Infrastructure.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78def8f4-5406-4a3a-a135-bd015ea6a80b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9403),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9409),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("731d905c-f6a3-48c5-8a98-50630ee9215f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9493),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9495),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("1aaa8c22-d076-4318-b836-0a09b9014199"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9501),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9502),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("63896fde-8755-4b73-9995-7589aebc1c7f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9516),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9517),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("5bde520c-70c0-4f5a-8008-b3e9f8bbc64b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9522),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9522),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("860ee2c8-b583-4abc-8ee3-5e9fba2b65c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9530),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9531),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("1d1f102e-ace6-465b-aadc-226bfa5ad359"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9535),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9536),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("cadaae7e-c7ea-478f-be31-a534d87d51c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9593),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9594),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("cc5cebbf-7313-4392-bd57-173c0c7d3194"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9598),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9599),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("a6fdc2a2-dd09-4f13-849d-4cdc307861b7"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9605),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9606),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("3369be5b-88bd-42ef-bdba-fef69872c1c0"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9610),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9611),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("33fca608-7598-45ea-9f6a-0d50b1b72fde"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9618),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9619),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("3384c688-b25b-4e10-8dac-dfa38d4ff4f5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9623),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9624),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("07de691d-2e60-4e40-bf55-f07682147dc5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9628),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9629),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("de54a5ed-8529-4413-b506-22833bc56f78"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9633),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9634),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("74c4774c-a40c-4701-9748-d0efae04e71d"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9638),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9639),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("67566eac-5bf4-4150-bbd1-061bedd71861"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9643),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9644),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("b99006ce-f829-42fd-9033-74e79589c2ed"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9649),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9650),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("67304698-5bf9-441a-9909-70f06c2642b5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9654),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9655),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("518414b4-97a5-494a-aa1a-25bad86f9a47"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9662),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(9663),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        });
                });

            modelBuilder.Entity("UntitledTechie.Infrastructure.Entities.PostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfLikes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d"),
                            Caption = "This is the 0 post",
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(4321),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            ImageId = new Guid("6e1bda32-25e5-4a9c-9837-f4b3aa6a970f"),
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(4635),
                            NumberOfLikes = 0
                        },
                        new
                        {
                            Id = new Guid("80595434-108f-4afb-888c-c2fad733781c"),
                            Caption = "This is the 1 post",
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5013),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            ImageId = new Guid("6e1bda32-25e5-4a9c-9837-f4b3aa6a970f"),
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5030),
                            NumberOfLikes = 1
                        },
                        new
                        {
                            Id = new Guid("a602c4aa-5876-4143-b47e-7635216a6270"),
                            Caption = "This is the 2 post",
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5045),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            ImageId = new Guid("6e1bda32-25e5-4a9c-9837-f4b3aa6a970f"),
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5046),
                            NumberOfLikes = 2
                        },
                        new
                        {
                            Id = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1"),
                            Caption = "This is the 3 post",
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5051),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            ImageId = new Guid("6e1bda32-25e5-4a9c-9837-f4b3aa6a970f"),
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5052),
                            NumberOfLikes = 3
                        },
                        new
                        {
                            Id = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1"),
                            Caption = "This is the 4 post",
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5056),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            ImageId = new Guid("6e1bda32-25e5-4a9c-9837-f4b3aa6a970f"),
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 123, DateTimeKind.Utc).AddTicks(5057),
                            NumberOfLikes = 4
                        });
                });

            modelBuilder.Entity("UntitledTechie.Infrastructure.Entities.SubCommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CreatorId");

                    b.ToTable("SubComment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2e7b5a2-80f0-495a-ac88-e96ad53be03c"),
                            CommentId = new Guid("78def8f4-5406-4a3a-a135-bd015ea6a80b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(3946),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(3953),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("a84b17a0-7852-4374-a103-d38e44fa41ba"),
                            CommentId = new Guid("78def8f4-5406-4a3a-a135-bd015ea6a80b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4031),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4032),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("5c003b7f-ea5b-4e78-ac17-b98b88b7eb85"),
                            CommentId = new Guid("78def8f4-5406-4a3a-a135-bd015ea6a80b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4039),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4040),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("062bf1d8-ad6b-4cc8-be32-922afb340342"),
                            CommentId = new Guid("78def8f4-5406-4a3a-a135-bd015ea6a80b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4045),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4046),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("c6ed8364-4418-4737-9c63-3bfe84abfcd0"),
                            CommentId = new Guid("78def8f4-5406-4a3a-a135-bd015ea6a80b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4050),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4051),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("f2802af7-9676-43c1-b46f-67614e15bee9"),
                            CommentId = new Guid("731d905c-f6a3-48c5-8a98-50630ee9215f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4059),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4060),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("097fbcc3-6087-4772-acfa-36da5c8fe37e"),
                            CommentId = new Guid("731d905c-f6a3-48c5-8a98-50630ee9215f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4064),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4065),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("f838a45d-8ae3-4bb5-8227-40fe9714b2fc"),
                            CommentId = new Guid("731d905c-f6a3-48c5-8a98-50630ee9215f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4077),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4078),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("eac233e9-b66e-4214-9d1f-a5cd7174b902"),
                            CommentId = new Guid("731d905c-f6a3-48c5-8a98-50630ee9215f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4082),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4083),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("dedea96d-f74d-4bee-8fa1-fbad4fb4bd41"),
                            CommentId = new Guid("731d905c-f6a3-48c5-8a98-50630ee9215f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4089),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4090),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("68fa93e2-9bd4-4eed-a85e-5d76211da3a6"),
                            CommentId = new Guid("1aaa8c22-d076-4318-b836-0a09b9014199"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4094),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4095),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("65eb6171-234c-4bd4-8912-febd66401bfe"),
                            CommentId = new Guid("1aaa8c22-d076-4318-b836-0a09b9014199"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4099),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4100),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("9617a830-beac-42ef-bcdc-8108a4cf24dc"),
                            CommentId = new Guid("1aaa8c22-d076-4318-b836-0a09b9014199"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4105),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4106),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("22135157-51e7-4c3a-8086-ab28db98d371"),
                            CommentId = new Guid("1aaa8c22-d076-4318-b836-0a09b9014199"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4110),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4111),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("d16afaf3-c46f-4b13-9ecc-e58b69b2665a"),
                            CommentId = new Guid("1aaa8c22-d076-4318-b836-0a09b9014199"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4115),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4116),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("3295676c-5e7d-44cc-856d-92601b159fd5"),
                            CommentId = new Guid("63896fde-8755-4b73-9995-7589aebc1c7f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4172),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4173),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("bc9292c6-bfdf-4cd0-8f01-1dea26dd0391"),
                            CommentId = new Guid("63896fde-8755-4b73-9995-7589aebc1c7f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4177),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4178),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("cc20f6d5-76ad-4b32-a39b-928f00856ea2"),
                            CommentId = new Guid("63896fde-8755-4b73-9995-7589aebc1c7f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4184),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4185),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("a53ca82d-8689-488a-8af3-1b2dd61110ca"),
                            CommentId = new Guid("63896fde-8755-4b73-9995-7589aebc1c7f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4189),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4190),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("37e629e7-1787-4e82-8d91-995b09e6f5bf"),
                            CommentId = new Guid("63896fde-8755-4b73-9995-7589aebc1c7f"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4194),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4195),
                            PostId = new Guid("33a52bc9-a469-4640-a3ec-7905e30ab82d")
                        },
                        new
                        {
                            Id = new Guid("5e93830c-db86-4c77-b058-8c0d04108933"),
                            CommentId = new Guid("5bde520c-70c0-4f5a-8008-b3e9f8bbc64b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4199),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4200),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("b96ae5b9-5ed4-4adf-91af-58c621dd4a1e"),
                            CommentId = new Guid("5bde520c-70c0-4f5a-8008-b3e9f8bbc64b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4204),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4205),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("0990ad2c-16e5-46b0-8b6b-2a95269eaa71"),
                            CommentId = new Guid("5bde520c-70c0-4f5a-8008-b3e9f8bbc64b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4209),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4210),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("e46ccad3-556c-48ee-8034-4fb18f428ed4"),
                            CommentId = new Guid("5bde520c-70c0-4f5a-8008-b3e9f8bbc64b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4217),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4218),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("75b545da-932b-4ec4-a914-193059fc9d71"),
                            CommentId = new Guid("5bde520c-70c0-4f5a-8008-b3e9f8bbc64b"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4222),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4223),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("24193aaa-8024-488e-80b5-6909245c6837"),
                            CommentId = new Guid("860ee2c8-b583-4abc-8ee3-5e9fba2b65c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4228),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4229),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("9da705a5-a30a-4962-af22-6453f01b043f"),
                            CommentId = new Guid("860ee2c8-b583-4abc-8ee3-5e9fba2b65c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4233),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4234),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("3351793c-c25f-4386-a5de-c4b5e6d32a49"),
                            CommentId = new Guid("860ee2c8-b583-4abc-8ee3-5e9fba2b65c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4238),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4239),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("b1cc4962-7b09-4a50-835f-d1ee01dac604"),
                            CommentId = new Guid("860ee2c8-b583-4abc-8ee3-5e9fba2b65c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4243),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4244),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("f4a05a13-7f04-4653-a2c7-e93079fedd53"),
                            CommentId = new Guid("860ee2c8-b583-4abc-8ee3-5e9fba2b65c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4248),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4249),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("23491524-b57f-4f5a-810b-655980e5a248"),
                            CommentId = new Guid("1d1f102e-ace6-465b-aadc-226bfa5ad359"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4254),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4254),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("712c7f82-c2e8-4e73-9ccc-81c2ccd352e4"),
                            CommentId = new Guid("1d1f102e-ace6-465b-aadc-226bfa5ad359"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4261),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4262),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("015b8960-34b5-40bf-a888-112ee36b42aa"),
                            CommentId = new Guid("1d1f102e-ace6-465b-aadc-226bfa5ad359"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4266),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4267),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("02e3de9b-56ad-4112-acc2-86e40e5e536f"),
                            CommentId = new Guid("1d1f102e-ace6-465b-aadc-226bfa5ad359"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4273),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4274),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("81888ea6-fc55-4a25-9aca-fe8d46f755a2"),
                            CommentId = new Guid("1d1f102e-ace6-465b-aadc-226bfa5ad359"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4278),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4279),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("5094fe7c-4dfd-4c9d-b553-51c75288b94b"),
                            CommentId = new Guid("cadaae7e-c7ea-478f-be31-a534d87d51c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4283),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4284),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("e1721426-ab29-49d4-8bf6-bb90a11b3a58"),
                            CommentId = new Guid("cadaae7e-c7ea-478f-be31-a534d87d51c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4288),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4289),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("f240acac-5e52-47d2-8622-990d39fe0ef4"),
                            CommentId = new Guid("cadaae7e-c7ea-478f-be31-a534d87d51c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4293),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4294),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("a83aecf0-c5f0-4829-b707-a5b82e504d5a"),
                            CommentId = new Guid("cadaae7e-c7ea-478f-be31-a534d87d51c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4299),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4300),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("0accc70d-8b65-4331-bd6c-3d32600bb813"),
                            CommentId = new Guid("cadaae7e-c7ea-478f-be31-a534d87d51c2"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4307),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4307),
                            PostId = new Guid("80595434-108f-4afb-888c-c2fad733781c")
                        },
                        new
                        {
                            Id = new Guid("317b8680-cfc4-4150-acdc-2dd78ad5a9e1"),
                            CommentId = new Guid("cc5cebbf-7313-4392-bd57-173c0c7d3194"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4312),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4313),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("e79e3c60-86ae-44c8-b6dd-bbbe38a8461b"),
                            CommentId = new Guid("cc5cebbf-7313-4392-bd57-173c0c7d3194"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4317),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4318),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("b1164342-1913-4fab-b79a-40a3f036228f"),
                            CommentId = new Guid("cc5cebbf-7313-4392-bd57-173c0c7d3194"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4323),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4324),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("b863509f-6e53-4a64-a2b5-80904dba852a"),
                            CommentId = new Guid("cc5cebbf-7313-4392-bd57-173c0c7d3194"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4328),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4329),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("8059fa67-1849-4db9-8779-a1c98f4cce6b"),
                            CommentId = new Guid("cc5cebbf-7313-4392-bd57-173c0c7d3194"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4333),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4334),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("e4e18fe9-e5f6-4d08-9c68-ebf5e1eb418f"),
                            CommentId = new Guid("a6fdc2a2-dd09-4f13-849d-4cdc307861b7"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4338),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4339),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("ea0d087a-9084-4b5a-a748-94c5244453fb"),
                            CommentId = new Guid("a6fdc2a2-dd09-4f13-849d-4cdc307861b7"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4343),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4344),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("863fb08c-3c7b-438e-bf9d-2ed1b66abd89"),
                            CommentId = new Guid("a6fdc2a2-dd09-4f13-849d-4cdc307861b7"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4351),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4352),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("6999137c-7d7f-4d37-8fe3-45ca94005d16"),
                            CommentId = new Guid("a6fdc2a2-dd09-4f13-849d-4cdc307861b7"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4356),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4357),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("5e672dac-9590-4fa4-9204-0b93ae8766bf"),
                            CommentId = new Guid("a6fdc2a2-dd09-4f13-849d-4cdc307861b7"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4361),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4362),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("9395cce8-dd5b-46b7-b620-8d02d1c6d080"),
                            CommentId = new Guid("3369be5b-88bd-42ef-bdba-fef69872c1c0"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4404),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4405),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("d8335c2c-9fe7-4a35-b1bf-39ccfbe8a712"),
                            CommentId = new Guid("3369be5b-88bd-42ef-bdba-fef69872c1c0"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4410),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4411),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("fe74fd9e-382b-4252-bf74-61944e8c8571"),
                            CommentId = new Guid("3369be5b-88bd-42ef-bdba-fef69872c1c0"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4415),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4416),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("c001dc46-af45-43fc-9709-2949bb32e9b7"),
                            CommentId = new Guid("3369be5b-88bd-42ef-bdba-fef69872c1c0"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4420),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4421),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("270bce07-e18b-4f11-875d-3dadad45dce8"),
                            CommentId = new Guid("3369be5b-88bd-42ef-bdba-fef69872c1c0"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4425),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4426),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("4340c389-8b11-45a9-86ae-1c1a8833f69d"),
                            CommentId = new Guid("33fca608-7598-45ea-9f6a-0d50b1b72fde"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4433),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4434),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("3b43da3c-5945-4972-aff2-d4493ad9a761"),
                            CommentId = new Guid("33fca608-7598-45ea-9f6a-0d50b1b72fde"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4438),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4439),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("e5af60f1-6d80-4fc3-888e-732f151dc453"),
                            CommentId = new Guid("33fca608-7598-45ea-9f6a-0d50b1b72fde"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4443),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4444),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("3d9f4228-25c9-4dd6-82e9-401400c4a7d3"),
                            CommentId = new Guid("33fca608-7598-45ea-9f6a-0d50b1b72fde"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4448),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4449),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("4c1d14c5-4e32-4847-ab10-50fb445b1c86"),
                            CommentId = new Guid("33fca608-7598-45ea-9f6a-0d50b1b72fde"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4453),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4454),
                            PostId = new Guid("a602c4aa-5876-4143-b47e-7635216a6270")
                        },
                        new
                        {
                            Id = new Guid("0b823702-be66-4660-8433-b6c7a749c3f4"),
                            CommentId = new Guid("3384c688-b25b-4e10-8dac-dfa38d4ff4f5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4459),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4460),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("d6f8c573-5a6b-42be-b07e-0467b834458a"),
                            CommentId = new Guid("3384c688-b25b-4e10-8dac-dfa38d4ff4f5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4464),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4465),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("ecfcade3-ce51-4aa9-ac5b-7bb740762c52"),
                            CommentId = new Guid("3384c688-b25b-4e10-8dac-dfa38d4ff4f5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4469),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4470),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("84021be6-ab2c-46f7-903b-e9c8b1b1c725"),
                            CommentId = new Guid("3384c688-b25b-4e10-8dac-dfa38d4ff4f5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4477),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4478),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("9021972f-f5b2-493a-913c-e539aecbf40a"),
                            CommentId = new Guid("3384c688-b25b-4e10-8dac-dfa38d4ff4f5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4482),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4483),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("5a6a0ac0-ed1f-4d3d-aa39-9b1424e29ba2"),
                            CommentId = new Guid("07de691d-2e60-4e40-bf55-f07682147dc5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4489),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4490),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("9c20b425-4457-4d79-b6d4-871f6c10beea"),
                            CommentId = new Guid("07de691d-2e60-4e40-bf55-f07682147dc5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4494),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4495),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("159ce869-9113-4fb8-937b-e68e9b7b868b"),
                            CommentId = new Guid("07de691d-2e60-4e40-bf55-f07682147dc5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4499),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4500),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("84ce0590-adf6-4123-9d39-6cd40b574b06"),
                            CommentId = new Guid("07de691d-2e60-4e40-bf55-f07682147dc5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4505),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4506),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("fa27833f-afef-45ab-9e5a-ea0357d82a95"),
                            CommentId = new Guid("07de691d-2e60-4e40-bf55-f07682147dc5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4510),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4511),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("07118b27-ae73-4012-8cc1-9193fbbc3511"),
                            CommentId = new Guid("de54a5ed-8529-4413-b506-22833bc56f78"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4515),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4516),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("8556b894-5fdb-4f6a-81d3-f7e0fb1b4a6e"),
                            CommentId = new Guid("de54a5ed-8529-4413-b506-22833bc56f78"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4523),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4524),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("2cec82dd-3df2-4d9f-8ee6-18c7a15a338c"),
                            CommentId = new Guid("de54a5ed-8529-4413-b506-22833bc56f78"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4528),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4529),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("b4c746a8-540d-475f-8e1f-1acf51f4e9e3"),
                            CommentId = new Guid("de54a5ed-8529-4413-b506-22833bc56f78"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4533),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4534),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("2279c50b-2b03-43a6-80f4-86410adb41b3"),
                            CommentId = new Guid("de54a5ed-8529-4413-b506-22833bc56f78"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4538),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4539),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("2e005342-4c2f-445b-bfac-b62279bb69f2"),
                            CommentId = new Guid("74c4774c-a40c-4701-9748-d0efae04e71d"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4543),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4544),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("b7fca1b3-ae71-4359-8770-4cecb469d5d1"),
                            CommentId = new Guid("74c4774c-a40c-4701-9748-d0efae04e71d"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4548),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4549),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("8b61ec8a-7c90-4ce3-bcf2-35f7fc73ad09"),
                            CommentId = new Guid("74c4774c-a40c-4701-9748-d0efae04e71d"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4553),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4554),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("30555b96-9a6d-4d72-961b-dcaf26c9d412"),
                            CommentId = new Guid("74c4774c-a40c-4701-9748-d0efae04e71d"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4558),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4559),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("0130acf8-68a1-4144-9074-5783cc6e4326"),
                            CommentId = new Guid("74c4774c-a40c-4701-9748-d0efae04e71d"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4566),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4567),
                            PostId = new Guid("e8ffcf5c-44fc-475f-80f9-694950ba65f1")
                        },
                        new
                        {
                            Id = new Guid("2a190bdf-6b33-4e40-91ef-c6a819738d1c"),
                            CommentId = new Guid("67566eac-5bf4-4150-bbd1-061bedd71861"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4571),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4572),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("1a49f628-0b6b-4aee-b958-ad7b2f8c38c8"),
                            CommentId = new Guid("67566eac-5bf4-4150-bbd1-061bedd71861"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4576),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4577),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("a34b20d1-2b6a-4e1e-af43-a5b360ebef2c"),
                            CommentId = new Guid("67566eac-5bf4-4150-bbd1-061bedd71861"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4581),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4582),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("cec136ed-4173-4f25-b067-11de81e76775"),
                            CommentId = new Guid("67566eac-5bf4-4150-bbd1-061bedd71861"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4586),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4587),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("12c3b6c3-6c16-4390-a406-afba2cf50a5a"),
                            CommentId = new Guid("67566eac-5bf4-4150-bbd1-061bedd71861"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4591),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4592),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("45087fcc-d863-40c8-9e22-1af5f448a6e4"),
                            CommentId = new Guid("b99006ce-f829-42fd-9033-74e79589c2ed"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4634),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4635),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("493661bf-b719-420e-b5e1-4534de3191d0"),
                            CommentId = new Guid("b99006ce-f829-42fd-9033-74e79589c2ed"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4639),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4640),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("52ae8955-e676-4070-aaa2-4ec274e1cc57"),
                            CommentId = new Guid("b99006ce-f829-42fd-9033-74e79589c2ed"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4646),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4647),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("e10bea97-7266-42da-8446-e6ea4ee50474"),
                            CommentId = new Guid("b99006ce-f829-42fd-9033-74e79589c2ed"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4651),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4652),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("95ab2119-0aa0-458c-9218-b2427b9e4033"),
                            CommentId = new Guid("b99006ce-f829-42fd-9033-74e79589c2ed"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4656),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4657),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("9a952fb9-264e-419c-a76a-44ab1ce2f03c"),
                            CommentId = new Guid("67304698-5bf9-441a-9909-70f06c2642b5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4661),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4662),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("c2c27ab7-b96f-4218-8eb1-72517b81560c"),
                            CommentId = new Guid("67304698-5bf9-441a-9909-70f06c2642b5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4666),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4667),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("32fa1a3f-ff8a-4263-ad7c-19fb03795562"),
                            CommentId = new Guid("67304698-5bf9-441a-9909-70f06c2642b5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4671),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4672),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("1ec8b623-b84b-42a2-a195-0fac9f3f0e9d"),
                            CommentId = new Guid("67304698-5bf9-441a-9909-70f06c2642b5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4676),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4677),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("f3202f4d-a00c-4da1-b362-d286464a13da"),
                            CommentId = new Guid("67304698-5bf9-441a-9909-70f06c2642b5"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4682),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4682),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("5714b4cd-815d-4cac-aaef-36f58c4e338f"),
                            CommentId = new Guid("518414b4-97a5-494a-aa1a-25bad86f9a47"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4689),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 0 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4690),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("f948bf44-a075-4ff0-aada-88514e82dc1d"),
                            CommentId = new Guid("518414b4-97a5-494a-aa1a-25bad86f9a47"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4694),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 1 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4695),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("c4e6af88-a84c-4b6f-9bc6-8a94f818d34f"),
                            CommentId = new Guid("518414b4-97a5-494a-aa1a-25bad86f9a47"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4699),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 2 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4700),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("e99191e0-b6a9-4370-9688-69b5829dd618"),
                            CommentId = new Guid("518414b4-97a5-494a-aa1a-25bad86f9a47"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4704),
                            CreatorId = new Guid("da9ccf25-5ec4-4ea8-a693-2668492dbdf9"),
                            Description = "This is the 3 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4705),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        },
                        new
                        {
                            Id = new Guid("e6b1d7bc-6921-4314-88ff-e80042c8e0a3"),
                            CommentId = new Guid("518414b4-97a5-494a-aa1a-25bad86f9a47"),
                            CreatedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4709),
                            CreatorId = new Guid("8413033b-987d-412a-9cb7-1b6f92c2c87d"),
                            Description = "This is the 4 sub-comment",
                            ModifiedDate = new DateTime(2020, 9, 15, 10, 31, 18, 124, DateTimeKind.Utc).AddTicks(4710),
                            PostId = new Guid("8c976373-0f5f-4688-a6e4-14741b57d6e1")
                        });
                });

            modelBuilder.Entity("UntitledTechie.Infrastructure.Entities.CommentEntity", b =>
                {
                    b.HasOne("UntitledTechie.Infrastructure.Entities.AccountEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UntitledTechie.Infrastructure.Entities.PostEntity", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UntitledTechie.Infrastructure.Entities.PostEntity", b =>
                {
                    b.HasOne("UntitledTechie.Infrastructure.Entities.AccountEntity", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UntitledTechie.Infrastructure.Entities.SubCommentEntity", b =>
                {
                    b.HasOne("UntitledTechie.Infrastructure.Entities.CommentEntity", null)
                        .WithMany("SubComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UntitledTechie.Infrastructure.Entities.AccountEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
